name: Automated Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  run-automated-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Maven Clean Install
        run: mvn clean install
