name: Automated Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven and Run Tests
        run:  mvn clean install
        working-directory: /

      - name: Check Test Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Branch cannot be merged."
            exit 1
          fi
        working-directory: /
