name: Automated Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Maven Clean Install
        run: mvn clean install

      - name: Check Test Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Branch cannot be merged."
            exit 1
          fi
